// <auto-generated />
using System;
using BaskanSensin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaskanSensin.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251207160836_VeriTabaniOlsuturuldu")]
    partial class VeriTabaniOlsuturuldu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaskanSensin.Models.HaritaKayit", b =>
                {
                    b.Property<int>("Haritaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Haritaid"));

                    b.Property<int>("Beklemesuresi")
                        .HasColumnType("int");

                    b.Property<Guid>("Cocukid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Slotno")
                        .HasColumnType("int");

                    b.Property<bool>("Tamamlanmadurumu")
                        .HasColumnType("bit");

                    b.Property<int>("Yapiid")
                        .HasColumnType("int");

                    b.HasKey("Haritaid");

                    b.HasIndex("Cocukid");

                    b.HasIndex("Yapiid");

                    b.ToTable("HaritaKayitlari");
                });

            modelBuilder.Entity("BaskanSensin.Models.Secenek", b =>
                {
                    b.Property<int>("Secenekid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Secenekid"));

                    b.Property<string>("Metin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Soruid")
                        .HasColumnType("int");

                    b.Property<int?>("Yetid")
                        .HasColumnType("int");

                    b.HasKey("Secenekid");

                    b.HasIndex("Soruid");

                    b.HasIndex("Yetid");

                    b.ToTable("Secenekler");

                    b.HasData(
                        new
                        {
                            Secenekid = 1,
                            Metin = "Mühendislik Ofisi",
                            Soruid = 1,
                            Yetid = 1
                        },
                        new
                        {
                            Secenekid = 2,
                            Metin = "Hastane",
                            Soruid = 1,
                            Yetid = 2
                        },
                        new
                        {
                            Secenekid = 3,
                            Metin = "Avukatlık Ofisi",
                            Soruid = 1,
                            Yetid = 3
                        },
                        new
                        {
                            Secenekid = 4,
                            Metin = "Sanat Atölyesi",
                            Soruid = 1,
                            Yetid = 4
                        },
                        new
                        {
                            Secenekid = 5,
                            Metin = "Spor Salonu",
                            Soruid = 1,
                            Yetid = 5
                        },
                        new
                        {
                            Secenekid = 6,
                            Metin = "Tüm mahallelere ücretsiz internet erişim ağı kurulması",
                            Soruid = 2,
                            Yetid = 1
                        },
                        new
                        {
                            Secenekid = 7,
                            Metin = "Şehrin tanıtımı için bir sanat festivali",
                            Soruid = 2,
                            Yetid = 2
                        },
                        new
                        {
                            Secenekid = 8,
                            Metin = "Şehirdeki tüm boş alanların kent bahçelerine dönüştürülmesi",
                            Soruid = 2,
                            Yetid = 3
                        },
                        new
                        {
                            Secenekid = 9,
                            Metin = "Yaşlılar için Destek Programları",
                            Soruid = 2,
                            Yetid = 4
                        },
                        new
                        {
                            Secenekid = 10,
                            Metin = "Şehir içi ulaşım için yüksek hızlı tramvay hattı projesi",
                            Soruid = 2,
                            Yetid = 5
                        },
                        new
                        {
                            Secenekid = 11,
                            Metin = "Temiz Su Arabaları Çağırma: Şehrin dört bir yanına temiz su dağıtan büyük tankerler göndeririz.",
                            Soruid = 3,
                            Yetid = 1
                        },
                        new
                        {
                            Secenekid = 12,
                            Metin = "Kırmızı Uyarı Bantları Çekme: Tüm kirli su basan sokaklara 'TEHLİKE!' bantları çekeriz.",
                            Soruid = 3,
                            Yetid = 2
                        },
                        new
                        {
                            Secenekid = 13,
                            Metin = "Dev Sünger Robotlar: Hızla çalışan, tüm suyu emen Dev Sünger Robotları icat edip göndeririz.",
                            Soruid = 3,
                            Yetid = 3
                        },
                        new
                        {
                            Secenekid = 14,
                            Metin = "Toprak Setler ve Akış Yönlendirme: Doğal toprak kullanarak geçici setler oluştururuz.",
                            Soruid = 3,
                            Yetid = 4
                        },
                        new
                        {
                            Secenekid = 15,
                            Metin = "Acil Vanayı Manüel Kapatma: Vanayı bizzat, elle ve en hızlı şekilde kapatmaları için talimat veririz.",
                            Soruid = 3,
                            Yetid = 5
                        },
                        new
                        {
                            Secenekid = 16,
                            Metin = "Gelecek Teknolojileri Araştıran Bir Merkez",
                            Soruid = 4,
                            Yetid = 1
                        },
                        new
                        {
                            Secenekid = 17,
                            Metin = "'Şehrin Renkleri' isimli Açık Hava Sanat Atölyesi",
                            Soruid = 4,
                            Yetid = 2
                        },
                        new
                        {
                            Secenekid = 18,
                            Metin = "Şehir Merkezine Kent Ormanı Projesi",
                            Soruid = 4,
                            Yetid = 3
                        },
                        new
                        {
                            Secenekid = 19,
                            Metin = "Büyük bir Liderlik ve İletişim Akademisi",
                            Soruid = 4,
                            Yetid = 4
                        },
                        new
                        {
                            Secenekid = 20,
                            Metin = "Çok Amaçlı Spor Salonu",
                            Soruid = 4,
                            Yetid = 5
                        },
                        new
                        {
                            Secenekid = 21,
                            Metin = "Kişiye Özel Akıllı Öğretmen",
                            Soruid = 5,
                            Yetid = 1
                        },
                        new
                        {
                            Secenekid = 22,
                            Metin = "Rüya Şehri Projesi",
                            Soruid = 5,
                            Yetid = 2
                        },
                        new
                        {
                            Secenekid = 23,
                            Metin = "Canlı Bitkiler Alanı",
                            Soruid = 5,
                            Yetid = 3
                        },
                        new
                        {
                            Secenekid = 24,
                            Metin = "Konuşma Alanı",
                            Soruid = 5,
                            Yetid = 4
                        },
                        new
                        {
                            Secenekid = 25,
                            Metin = "Yer Çekimsiz Egzersiz Bölgesi",
                            Soruid = 5,
                            Yetid = 5
                        },
                        new
                        {
                            Secenekid = 26,
                            Metin = "Robotik ve Yapay Zeka Laboratuvarı Seferberliği",
                            Soruid = 6,
                            Yetid = 1
                        },
                        new
                        {
                            Secenekid = 27,
                            Metin = "'Tasarım Odaklı Düşünme' Müfredatı",
                            Soruid = 6,
                            Yetid = 2
                        },
                        new
                        {
                            Secenekid = 28,
                            Metin = "Zorunlu 'Açık Hava Okulları' Sistemi",
                            Soruid = 6,
                            Yetid = 3
                        },
                        new
                        {
                            Secenekid = 29,
                            Metin = "'Geleceğin Liderleri' Mentorluk Programı",
                            Soruid = 6,
                            Yetid = 4
                        },
                        new
                        {
                            Secenekid = 30,
                            Metin = "'Günde İki Saat Hareket' Eğitimi",
                            Soruid = 6,
                            Yetid = 5
                        },
                        new
                        {
                            Secenekid = 31,
                            Metin = "Laboratuvarda ölçümler yapacak bir biyolog",
                            Soruid = 7,
                            Yetid = 1
                        },
                        new
                        {
                            Secenekid = 32,
                            Metin = "Engelli bireylerin hastanede rahat hareket edebilmesi için alan yerleşimini geliştirecek bir mimar",
                            Soruid = 7,
                            Yetid = 2
                        },
                        new
                        {
                            Secenekid = 33,
                            Metin = "Terapi bahçesi tasarlayacak bir bahçıvan",
                            Soruid = 7,
                            Yetid = 3
                        },
                        new
                        {
                            Secenekid = 34,
                            Metin = "Çalışanları yönlendirecek poliklinik sorumlusu",
                            Soruid = 7,
                            Yetid = 4
                        },
                        new
                        {
                            Secenekid = 35,
                            Metin = "Ameliyatları yapacak bir cerrah",
                            Soruid = 7,
                            Yetid = 5
                        },
                        new
                        {
                            Secenekid = 36,
                            Metin = "Hastaların tansiyonunu ölçecek cihaz",
                            Soruid = 8,
                            Yetid = 1
                        },
                        new
                        {
                            Secenekid = 37,
                            Metin = "Hastaları yönlendirmek için dijital ekran sistemi",
                            Soruid = 8,
                            Yetid = 2
                        },
                        new
                        {
                            Secenekid = 38,
                            Metin = "Giriş odasının havasını temizleyecek makine",
                            Soruid = 8,
                            Yetid = 3
                        },
                        new
                        {
                            Secenekid = 39,
                            Metin = "Hastaların hangi doktora gideceğini söyleyen makine",
                            Soruid = 8,
                            Yetid = 4
                        },
                        new
                        {
                            Secenekid = 40,
                            Metin = "Yaşlı hastaların kolay taşınması için tekerlekli sandalye",
                            Soruid = 8,
                            Yetid = 5
                        },
                        new
                        {
                            Secenekid = 41,
                            Metin = "Günlük hasta artışlarını takip eden sistem",
                            Soruid = 9,
                            Yetid = 1
                        },
                        new
                        {
                            Secenekid = 42,
                            Metin = "Hastanede kaygan ve ıslak alanlara uyarı levhaları hazırlamak",
                            Soruid = 9,
                            Yetid = 2
                        },
                        new
                        {
                            Secenekid = 43,
                            Metin = "İç mekanda kış bahçesi tasarımı",
                            Soruid = 9,
                            Yetid = 3
                        },
                        new
                        {
                            Secenekid = 44,
                            Metin = "Hastalar artacağı için danışma çalışanlarının artırılması",
                            Soruid = 9,
                            Yetid = 4
                        },
                        new
                        {
                            Secenekid = 45,
                            Metin = "Buzlanma durumunda dış alanın nasıl temizleneceğini kararlaştırmak",
                            Soruid = 9,
                            Yetid = 5
                        },
                        new
                        {
                            Secenekid = 46,
                            Metin = "Puzzle seti",
                            Soruid = 10,
                            Yetid = 1
                        },
                        new
                        {
                            Secenekid = 47,
                            Metin = "Sanatsal bir tablo",
                            Soruid = 10,
                            Yetid = 2
                        },
                        new
                        {
                            Secenekid = 48,
                            Metin = "Gül Fidanı",
                            Soruid = 10,
                            Yetid = 3
                        },
                        new
                        {
                            Secenekid = 49,
                            Metin = "Üzerinde çalışanın isim ve soy ismi yazan bir ajanda",
                            Soruid = 10,
                            Yetid = 4
                        },
                        new
                        {
                            Secenekid = 50,
                            Metin = "Boyun masaj cihazı",
                            Soruid = 10,
                            Yetid = 5
                        },
                        new
                        {
                            Secenekid = 51,
                            Metin = "Elektrik kesintisinin nedenini araştırmak",
                            Soruid = 11,
                            Yetid = 1
                        },
                        new
                        {
                            Secenekid = 52,
                            Metin = "Karanlıkta parlayan acil çıkış kapısı levhalarını kontrol etmek",
                            Soruid = 11,
                            Yetid = 2
                        },
                        new
                        {
                            Secenekid = 53,
                            Metin = "Karanlık bölgelerde hastaların düşmemesi için taşınabilir ışıkların açılması",
                            Soruid = 11,
                            Yetid = 3
                        },
                        new
                        {
                            Secenekid = 54,
                            Metin = "Hasta ve yakınlarına “hepimiz kontrol altındayız” duyurusu yapmak",
                            Soruid = 11,
                            Yetid = 4
                        },
                        new
                        {
                            Secenekid = 55,
                            Metin = "Hastaları taşımak için acil destek ekibi yönlendirmek",
                            Soruid = 11,
                            Yetid = 5
                        },
                        new
                        {
                            Secenekid = 56,
                            Metin = "Ameliyathane ve Kritik Alan Stok Kontrolü",
                            Soruid = 12,
                            Yetid = 1
                        },
                        new
                        {
                            Secenekid = 57,
                            Metin = "Hızlı Acil Durum Noktası Kurulumu (Düzeni)",
                            Soruid = 12,
                            Yetid = 2
                        },
                        new
                        {
                            Secenekid = 58,
                            Metin = "Acil Durum Personel Çağrısı",
                            Soruid = 12,
                            Yetid = 4
                        },
                        new
                        {
                            Secenekid = 59,
                            Metin = "Doğal Ortamda Sakinleştirme",
                            Soruid = 12,
                            Yetid = 3
                        },
                        new
                        {
                            Secenekid = 60,
                            Metin = "Yatak Sayısını Arttırma",
                            Soruid = 12,
                            Yetid = 5
                        });
                });

            modelBuilder.Entity("BaskanSensin.Models.Skor", b =>
                {
                    b.Property<int>("Skorid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Skorid"));

                    b.Property<int>("Analitikp")
                        .HasColumnType("int");

                    b.Property<string>("Baskinyet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("Cocukid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Dogap")
                        .HasColumnType("int");

                    b.Property<int>("Sanatp")
                        .HasColumnType("int");

                    b.Property<int>("Sosyalp")
                        .HasColumnType("int");

                    b.Property<int>("Sporp")
                        .HasColumnType("int");

                    b.HasKey("Skorid");

                    b.HasIndex("Cocukid");

                    b.ToTable("Skorlar");
                });

            modelBuilder.Entity("BaskanSensin.Models.Soru", b =>
                {
                    b.Property<int>("Soruid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Soruid"));

                    b.Property<string>("Metin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Soruid");

                    b.ToTable("Sorular");

                    b.HasData(
                        new
                        {
                            Soruid = 1,
                            Metin = "Sevgili Başkan! Seninle şehrimizin ilk binasını oluşturmak istiyorum ama nereden başlayacağım konusunda kafam karışık. Haydi bize bir bina seç ve birlikte şehrimizin ilk binasını inşa etmeye başlayalım."
                        },
                        new
                        {
                            Soruid = 2,
                            Metin = "Mühendislik ofisimize devlet tarafından büyük bir fon tanımlandı. Ekibiniz bu fonu kullanmak üzere beş farklı proje önerisi sundu. Şimdi seninle bu farklı proje alanlarını inceleyeceğiz.\n\nBaşkanım, bu önemli kaynağı şehrin gelecekteki ruhunu oluşturmak için hangi projeye yatırmalıyız?"
                        },
                        new
                        {
                            Soruid = 3,
                            Metin = "Başkanım! Şehrin en eski su borusu büyük bir yağmurda patladı! Kirli su, şehirdeki parkın ve oyun alanının etrafını sardı. İnsanlar üzgün ve hasta olmaktan korkuyor. Senin mühendislik bilgin bu şehrin kaderini değiştirebilir.\n\nBaşkanım, yardımcılarınıza ilk olarak hangi ışık hızında emri verirsiniz?"
                        },
                        new
                        {
                            Soruid = 4,
                            Metin = "Başkanım yaptığımız çalışmalar devletimiz tarafından büyük bir övgüyle karşılanıyor. Mühendis arkadaşlarınız tarafından da oldukça popülersiniz. Bir mühendis arkadaşımız yardımcı olmamız için bazı projeler gönderdi. Bu projelerden hangisini kabul etmeliyiz?"
                        },
                        new
                        {
                            Soruid = 5,
                            Metin = "Vay canına, Başkanım! Hayal gücümüzü kullanarak gerçekleştireceğimiz sihirli bir göreve hazır mısın? Şehrinize, anında ve kalıcı olarak mucizeler yaratabilen 'Süper Dönüşüm Kristali' siz başarılı mühendisimize hediye edildi. Bu kristal, şehrin sadece tek bir özelliğini mükemmel bir hale getirecek.\n\nSüper Kahraman Başkanım, şehrinizi geleceğe ışınlamak için bu tek ve güçlü kristali hangi alanda kullanırsınız?"
                        },
                        new
                        {
                            Soruid = 6,
                            Metin = "Başkanım, uluslararası bir rapor, şehrimiz için kırmızı alarm verdi! Şehrinizin gençleri, gelecekteki küresel rekabetteki en kritik becerilerde (eleştirel düşünme, ekip çalışması, fiziksel sağlık) diğer büyük şehirlerin gerisinde kalmış durumda. Mevcut eğitim ve gelişim sistemi artık çağın gereklerini karşılayamıyor.\n\nBaşkanım, şehrin gençlerini hızla geleceğe hazırlamak ve bu krizi tersine çevirmek için hangi köklü reformu başlatırsınız?"
                        },
                        new
                        {
                            Soruid = 7,
                            Metin = "Yeni hastanen harika görünüyor Başkan! Hadi hastanene yeni çalışanlar ekleyip daha güzel hizmet verelim. İlk önce kimi işe alalım?"
                        },
                        new
                        {
                            Soruid = 8,
                            Metin = "Merhaba Başkan! Yeni hastanemize hastalar gelmeye başladı. Giriş kapısına yeni bir cihaz almalıyız. Hangisinden başlayalım?"
                        },
                        new
                        {
                            Soruid = 9,
                            Metin = "Başkan hastanemiz çok iyi durumda ama kış geliyor. Tedbirimizi elden bırakmamalıyız. Kış mevsimine ve artacak hastalara hazırlanmalıyız. Nereden başlayalım?"
                        },
                        new
                        {
                            Soruid = 10,
                            Metin = "Başkan, bayram yaklaşıyor. Hastanedeki çalışanlar bizim için çok önemli. Onları ve ailelerini mutlu etmek için hastane çalışanlarına bir hediye belirleyelim!"
                        },
                        new
                        {
                            Soruid = 11,
                            Metin = "HAY AKSİ! Hastanemiz tüm imkanlarını halka sağlamak için çok çalışıyor ama yolunda gitmeyen bir şeyler var. Başkan, hastanede aniden elektrikler kesildi. Şu an ne yapmalıyız? Yardımınıza ihtiyacım var."
                        },
                        new
                        {
                            Soruid = 12,
                            Metin = "Şehrin hemen dışındaki bir otoyolda büyük bir zincirleme kaza oldu. Durumu ağır olan hastalar dâhil çok sayıda yaralı var ve acil servise aynı anda akın etmeye başladılar. Hastanemizdeki yatak ve personel kapasitesi hızla yetersiz gelmeye başlıyor. Başkanım, yardımcılarınıza ilk olarak hangi emri verirsiniz?"
                        });
                });

            modelBuilder.Entity("BaskanSensin.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VeliId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId");

                    b.HasIndex("VeliId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BaskanSensin.Models.Yapi", b =>
                {
                    b.Property<int>("Yapid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Yapid"));

                    b.Property<int>("Beklemesuresi")
                        .HasColumnType("int");

                    b.Property<string>("BilgiKarti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Binaad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Yapid");

                    b.ToTable("Yapilar");

                    b.HasData(
                        new
                        {
                            Yapid = 1,
                            Beklemesuresi = 15,
                            BilgiKarti = "Hastane, insanların daha sağlıklı olması için onlara yardım eden büyük ve önemli bir binadır.\r\nBu bina, hasta veya yaralı olduğumuz zamanlarda  iyileşmemize yardım eden ve doktorların, hemşirelerin ve diğer sağlık kahramanlarının çalıştığı özel bir yerdir. ",
                            Binaad = "Hastane",
                            Resim = "hastane.jpeg"
                        },
                        new
                        {
                            Yapid = 2,
                            Beklemesuresi = 15,
                            BilgiKarti = "Şehirdeki  yolları, kaldırımları ve parkları  yapan, bozulan yerleri tamir eden ve herkesin güvenle yürümesini sağlayan yerdir.",
                            Binaad = "Mühendislik Ofisi",
                            Resim = "garden.png"
                        },
                        new
                        {
                            Yapid = 3,
                            Beklemesuresi = 15,
                            BilgiKarti = "Avukatlar,  insanların kurallara uygun ve adil bir şekilde muamele görmesini sağlamak için çalışırlar. ",
                            Binaad = "Avukatlık Bürosu",
                            Resim = "library.png"
                        },
                        new
                        {
                            Yapid = 4,
                            Beklemesuresi = 15,
                            BilgiKarti = "İnsanların fikirleri gerçeğe dönüştürdüğü ve hayatımızı daha güzel, eğlenceli ve ilginç hale getirildiği yerlerdir. Bu yerlerde resim, müzik, tiyatro gibi birçok alanda çalışmalar yapılır.",
                            Binaad = "Sanat Atölyesi",
                            Resim = "garden.png"
                        },
                        new
                        {
                            Yapid = 5,
                            Beklemesuresi = 15,
                            BilgiKarti = "İnsanların vücutlarını güçlendirmek için koştuğu, zıpladığı ve egzersiz yaptığı yerdir.",
                            Binaad = "Spor Salonu",
                            Resim = "gym.jpeg"
                        });
                });

            modelBuilder.Entity("BaskanSensin.Models.Yetenek", b =>
                {
                    b.Property<int>("Yetid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Yetid"));

                    b.Property<string>("Yetad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Yetid");

                    b.ToTable("Yetenekler");

                    b.HasData(
                        new
                        {
                            Yetid = 1,
                            Yetad = "Analitik Zeka"
                        },
                        new
                        {
                            Yetid = 2,
                            Yetad = "Sanatsal Zeka"
                        },
                        new
                        {
                            Yetid = 3,
                            Yetad = "Doğa Zekası"
                        },
                        new
                        {
                            Yetid = 4,
                            Yetad = "Sosyal Zeka"
                        },
                        new
                        {
                            Yetid = 5,
                            Yetad = "Bedensel Zeka"
                        });
                });

            modelBuilder.Entity("BaskanSensin.Models.HaritaKayit", b =>
                {
                    b.HasOne("BaskanSensin.Models.User", "Cocuk")
                        .WithMany()
                        .HasForeignKey("Cocukid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaskanSensin.Models.Yapi", "Yapi")
                        .WithMany()
                        .HasForeignKey("Yapiid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cocuk");

                    b.Navigation("Yapi");
                });

            modelBuilder.Entity("BaskanSensin.Models.Secenek", b =>
                {
                    b.HasOne("BaskanSensin.Models.Soru", "Soru")
                        .WithMany("Secenekler")
                        .HasForeignKey("Soruid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaskanSensin.Models.Yetenek", "Yetenek")
                        .WithMany()
                        .HasForeignKey("Yetid");

                    b.Navigation("Soru");

                    b.Navigation("Yetenek");
                });

            modelBuilder.Entity("BaskanSensin.Models.Skor", b =>
                {
                    b.HasOne("BaskanSensin.Models.User", "Cocuk")
                        .WithMany()
                        .HasForeignKey("Cocukid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cocuk");
                });

            modelBuilder.Entity("BaskanSensin.Models.User", b =>
                {
                    b.HasOne("BaskanSensin.Models.User", "Veli")
                        .WithMany()
                        .HasForeignKey("VeliId");

                    b.Navigation("Veli");
                });

            modelBuilder.Entity("BaskanSensin.Models.Soru", b =>
                {
                    b.Navigation("Secenekler");
                });
#pragma warning restore 612, 618
        }
    }
}
